### ISSUE TITLE
Error on starting python 

### ISSUE THREAD

**Issue by developer2013** [cheezwinkle/Online-Store-Price-Checker#1]
Hello, 

i would like to run the code, but python give my an Error on: 

sudo python3 pricecheck.py

--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 978, in emit
    msg = self.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 565, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.4/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "pricecheck.py", line 35, in <module>
    logging.info(len(elems), 'prices were found')
Message: 3
Arguments: ('prices were found',)

could you help me? 

Thanks
Carsten

**Comment by cheezwinkle** [comment]
Hi Carsten,

I will take a look at this.

Cheers.

**Comment by cheezwinkle** [comment]
Hi Carsten,

For some reason the string formatting for the logging on line 35 wasn't quite right. I've fixed it so please try it out and let me know how it goes.

Thanks!

**Comment by developer2013** [comment]
Hello, 

now it's working. 

but i get an error for this Site:

url=http://www.rctech.de/tbs-unify-pro-hv-race-fpv-video-sender-team-blacksheep-sma.html
html_tags=span[span="price"]

is it why the price is with comma? 

Greets

**Comment by cheezwinkle** [comment]
The comma will definitely cause issues. I can make it handle commas and test it with the website you have provided. Hopefully it will be fully European-compatible after. :)

**Comment by cheezwinkle** [comment]
Hi Carsten,

This should work now. Tested using below settings.

```
[Webpage Settings]
url=http://www.rctech.de/tbs-unify-pro-hv-race-fpv-video-sender-team-blacksheep-sma.html
html_tags=#product-price-780 .price
standard_price=34,90
```

There is a minor issue of when the email is sent, it will show the price with a '$' instead of '€'. I will fix this soon.

Thanks!

**Comment by developer2013** [comment]
wow, that sounds great i will test it and give you an info. 

no, Thank u

**Comment by developer2013** [comment]
it worked for me! great work.
