### ISSUE TITLE
Error via crontab -e? 

### ISSUE THREAD

**Issue by developer2013** [cheezwinkle/Online-Store-Price-Checker#2]
Hello, 

when i try to get the script working via crontab it shows me the error: 

`Traceback (most recent call last):
  File "/home/pi/hobbyking-graphene/pricecheck.py", line 5, in <module>
    from sendemail import sendemail
  File "/home/pi/hobbyking-graphene/sendemail.py", line 8, in <module>
    emailsettings = config['Email Settings']
  File "/usr/lib/python3.4/configparser.py", line 937, in __getitem__
    raise KeyError(key)
KeyError: 'Email Settings'`

code for crontab: python3 /home/pi/hobbyking-graphene/pricecheck.py

thanks
Carsten

**Comment by cheezwinkle** [comment]
Hi Carsten,

I believe it's because it can't find config.ini when running via cron, as it is not checking for it in the same directory.

I will make a change and test it out over the weekend and let you know when it's done. 

Thanks!

**Comment by developer2013** [comment]
Hello  cheezwinkle, 

i got it working. i set the absolute path to the config.ini in the sendemail.py and priceckeck.py and now it's working. 

nice Weekend

**Comment by cheezwinkle** [comment]
Great work! Thanks for letting me know.
